### ISSUE TITLE
Throw focused window shortcuts not working after MacOS 12.2 upgrade

### ISSUE THREAD

**Issue by NZLostboy** [ianyh/Amethyst#1192]
After upgrading to MacOS 12.2, the 'throw focused window to spaces' doesn't seem to be working anymore.
No error shown, but it just doesn't shift the window to the specified space. 
The 'Swap focused window' shortcuts seem to be working fine.
I can still manually shift windows between spaces using the Apple default shortcuts (Click title then ctrl #).

**Versions:**
MacOS 12.2
Amethyst 0.15.5 (92)

**Reproduction:**
Using the versions above, set your short cuts for 'throw focused window to spaces', restart Amethyst, attempt to throw a window to a new space and observe it doesn't work.

**Debug Info**
❯ /Applications/Amethyst.app/Contents/MacOS/Amethyst --debug-info
Version: 0.15.5 (92)

OS version: Version 12.2 (Build 21D49)

Screens:
	(0.0, 0.0, 2560.0, 1080.0) [(0.0, 0.0, 2560.0, 1080.0)]

Configuration:
window-minimum-width: 0
screen-padding-left: 0
enables-layout-hud: 0
mouse-swaps-windows: 1
mouse-follows-focus: 1
floating: (
)
mod1: (
    option,
    shift
)
screen-padding-bottom: 0
window-resize-step: 5
mod2: (
    option,
    shift,
    control
)
layouts: (
    tall,
    wide,
    fullscreen,
    column
)
debug-layout-info: 0
screen-padding-right: 0
follow-space-thrown-windows: 0
use-canary-build: 1
float-small-windows: 1
window-margin-size: 0
window-minimum-height: 0
new-windows-to-main: 0
screen-padding-top: 0
window-margins: 0
floating-is-blacklist: 1
enables-layout-hud-on-space-change: 0
focus-follows-mouse: 0
restore-layouts-on-launch: 1
mouse-resizes-windows: 1
ignore-menu-bar: 0

*** Additional: ***
I haven't changed my configuration in any way recently, has been working for 6 months until the update.

**Comment by ClonedOne** [comment]
Can confirm, same versions of MacOs and Amethyst, the "throw focused window" shortcuts are not working

**Comment by antoniopantaleo** [comment]
Take a look here #1184 
The problem has been fixed. Just waiting for a new release

**Comment by mwz** [comment]
Hi @ianyh, any chance we could get a new release published with this fix?

**Comment by danielxul** [comment]
I can confirm this issue.

**Comment by simonedamico** [comment]
Please, release 😭

**Comment by EttVenter** [comment]
Please! 😅

**Comment by danielxul** [comment]
Release it, please.

**Comment by hetul** [comment]
FYI - I'm pretty sure that 12.2.1 breaks this feature again, even after the posted fix 😠 

Seems like Apple has been making changes to those internal APIs

**Comment by legat1** [comment]
> Take a look here #1184 The problem has been fixed. Just waiting for a new release

Just tried this fix building development branch but unfortunately this issue is still here 😭

**Comment by rublev** [comment]
Lmao I spent like 3 hours on this before realizing wait... maybe its the OS upgrade. AHhhhh

**Comment by sloterplas** [comment]
hi @ianyh, are you actively working on this project?

**Comment by ianyh** [comment]
Short answer is yes, but my availability is spotty due to other responsibilities.

**Comment by dzanotto** [comment]
It looks like I've fixed the problem locally by using CGSMoveWindowsToManagedSpace instead of CGSAddWindowsToSpaces + CGSRemoveWindowsFromSpaces.
To do that in a proper way, I think that CGSMoveWindowsToManagedSpace should be added to CGSSpace.h that comes with Silica (but maybe I'm completely wrong...).
Does it make sense @ianyh?

**Comment by NZLostboy** [comment]
The development branch build seems to have solved my problem, thanks @dzanotto 
For anyone not wanting to build their own, you will have to wait for the next release
- Edited, turns out it didn't fix it properly, it only worked for a while

**Comment by dzanotto** [comment]
> The development branch build seems to have solved my problem, thanks @dzanotto For anyone not wanting to build their own, you will have to wait for the next release

This puzzles me a bit
I was able to reproduce the problem with the app built from the development branch.
Then I've fixed it by applying the changes mentioned in the previous comment.
So I don't know :(

**Comment by mruell** [comment]
@ianyh 

is there already a plan for the next release?

Best,
Marvin

**Comment by legat1** [comment]
> > The development branch build seems to have solved my problem, thanks @dzanotto For anyone not wanting to build their own, you will have to wait for the next release
> 
> This puzzles me a bit I was able to reproduce the problem with the app built from the development branch. Then I've fixed it by applying the changes mentioned in the previous comment. So I don't know :(

Thank you for investigating this issue, I have tried your fix but without success. But maybe I did something wrong. Did you push your fix into a branch somewhere?
This also puzzles me a bit, this issue seems fixed for some people with the development branch but not for others (at least for you and me). 
I hope this issue will be fixed soon, I was using it a lot.

**Comment by ianyh** [comment]
There's a different issue that @dzanotto fixed involving switching spaces that people could be confusing this with.

@dzanotto, I'll give your change with the new API a shot. That's a nice find.

I did upgrade to 12.2 last night to force myself to fix it and get a release out. 😂💀

**Comment by dzanotto** [comment]
> There's a different issue that @dzanotto fixed involving switching spaces that people could be confusing this with.

Yes, you're probably right.

> @dzanotto, I'll give your change with the new API a shot. That's a nice find.

I've created a PR for CGSInternal and one for Amethyst. I hope it can help.

> I did upgrade to 12.2 last night to force myself to fix it and get a release out. 😂💀

This is a good strategy to fix bugs, painful but good 🤣

**Comment by legat1** [comment]
I tested @dzanotto fix with success, so I can confirm the fix.
Thank you @dzanotto.

**Comment by NZLostboy** [comment]
> > The development branch build seems to have solved my problem, thanks @dzanotto For anyone not wanting to build their own, you will have to wait for the next release
> 
> This puzzles me a bit I was able to reproduce the problem with the app built from the development branch. Then I've fixed it by applying the changes mentioned in the previous comment. So I don't know :(

Puzzled me too, I swear it was working for a while after I built it, today its not working again. I edited my comment, you are right its not fixed.

**Comment by andbenn** [comment]
I recently upgraded to Monterey 12.0.1 and hit this.  It seems if I use the keybinding twice to move a window to another space, the second action moves the window.  The first key action does something, as I see other windows on the current space adjust - but I haven't had time to figure that out.

**Comment by NZLostboy** [comment]
> I recently upgraded to Monterey 12.0.1 and hit this. It seems if I use the keybinding twice to move a window to another space, the second action moves the window. The first key action does something, as I see other windows on the current space adjust - but I haven't had time to figure that out.

If you build from the dev branch, this has been fixed :) Otherwise you will have to wait for a new release

**Comment by lwouis** [comment]
@dzanotto the `CGSMoveWindowsToManagedSpace` doesn't seem to move fullscreen windows. The `CGSAddWindowsToSpaces` API did move them.

How did you work around this limitation? It's a blocker for my project (https://github.com/lwouis/alt-tab-macos), and I'm curious how you guys dealt with `CGSAddWindowsToSpaces` being broken from macOS 12.2 onward.

**Comment by dzanotto** [comment]
> @dzanotto the `CGSMoveWindowsToManagedSpace` doesn't seem to move fullscreen windows. The `CGSAddWindowsToSpaces` API did move them.
> 
> How did you work around this limitation? It's a blocker for my project (https://github.com/lwouis/alt-tab-macos), and I'm curious how you guys dealt with `CGSAddWindowsToSpaces` being broken from macOS 12.2 onward.

I confirm it doesn't seem to move fullscreen windows and TBH I don't even know if Amethyst was ever supposed to do so 😅
