### ISSUE TITLE
Throw focused window to space (left/right) is buggy on a multi-monitor setup

### ISSUE THREAD

**Issue by 27medkamal** [ianyh/Amethyst#1315]
**Describe the bug**
Throw focused window to space (left/right) is buggy on a multi-monitor setup. If I don't connect any external monitors to my laptop, all works fine, but when i have a multi monitor setup (2 extra monitors), those 2 shorcuts throw the focused window to the laptop's monitor instead

**Applications:**
All

**To Reproduce**
Described above

**Expected behavior**
The 2 shortcuts should throw the focused window to the space (left/right) on the same monitor

**Screenshots**
NA

**Versions:**
 - macOS: 12.5.1
 - Amethyst: 0.16.0
 
**Debug Info**
```
Version: 0.16.0 (94)

OS version: Version 12.5.1 (Build 21G83)

Screens:
        (0.0, 0.0, 1512.0, 982.0) [(0.0, 0.0, 1512.0, 982.0)]
        (-3008.0, -401.0, 3008.0, 1692.0) [(-3008.0, -309.0, 3008.0, 1692.0)]
        (-4700.0, -1441.0, 1692.0, 3008.0) [(-4700.0, -585.0, 1692.0, 3008.0)]

Configuration:
mod1: (
    option,
    shift
)
floating: (
        {
        id = "com.apple.systempreferences";
        "window-titles" =         (
        );
    },
        {
        id = "com.audient.id";
        "window-titles" =         (
        );
    },
        {
        id = "com.aone.keka";
        "window-titles" =         (
        );
    },
        {
        id = "com.logitech.Logi-Options";
        "window-titles" =         (
        );
    },
        {
        id = "*Alfred*";
        "window-titles" =         (
        );
    }
)
follow-space-thrown-windows: 1
debug-layout-info: 0
window-minimum-width: 0
window-margins: 1
enables-layout-hud: 1
use-canary-build: 0
mod2: (
    option,
    shift,
    control
)
mouse-swaps-windows: 1
screen-padding-left: 0
ignore-menu-bar: 0
layouts: (
    tall,
    wide,
    fullscreen,
    column
)
window-minimum-height: 0
mouse-follows-focus: 1
floating-is-blacklist: 1
restore-layouts-on-launch: 1
new-windows-to-main: 1
window-margin-size: 10
screen-padding-bottom: 0
screen-padding-top: 0
float-small-windows: 1
smart-window-margins: 1
enables-layout-hud-on-space-change: 1
window-resize-step: 5
mouse-resizes-windows: 1
screen-padding-right: 0
focus-follows-mouse: 0
```

**Comment by danielxul** [comment]
I have the same issue, and I've opened an issue several months ago. No progress on this matter, yet. Sadly.

**Comment by 27medkamal** [comment]
This seems to be a bug in the latest release. I manually downgraded to the version 0.15.6 and this issues disappeared

**Comment by artmazi** [comment]
@27medkamal Can you guide me how to downgrade it? It does not show any other version on cask.

**Comment by 27medkamal** [comment]
From the assets [here](https://github.com/ianyh/Amethyst/releases/tag/v0.15.6)

**Comment by JordyScript** [comment]
I'm having the same issue, but I have had it for a while now. It was not introduced with 0.16.0 but was there on 0.15.6 and maybe even earlier (I only started using Amethyst on version 0.15.6). I upgraded to 0.16.0 recently to see if it resolved the issue, but it is still present for me. I'm on macOS 13.1 Ventura.

**Comment by ianyh** [comment]
Addressed in #1408

**Comment by 27medkamal** [comment]
This is still broken on the latest version 0.18.0

**Comment by JordyScript** [comment]
I can confirm it is still broken on 0.18.0

When I press the shortcut to throw the focused window on an external display to the next space on that display, it will instead be thrown to one of the spaces on the primary display. 

On the primary display I can throw any window to the next or previous space on that display.

Throwing windows to the previous/next display works fine from any display.

**Comment by ianyh** [comment]
The fix will be in 0.19.0.

**Comment by JordyScript** [comment]
Thank you ! :)

**Comment by JordyScript** [comment]
Everything works for me with the latest update! Thanks :)

**Comment by 27medkamal** [comment]
I can confirm it's working on 0.19.0 as well. Thanks for the fix.
