### ISSUE TITLE
Multi-monitor regression after v15.6.0

### ISSUE THREAD

**Issue by tombuntus** [ianyh/Amethyst#1436]
**Describe the bug**
On every version following 15.6.0 the behavior when throwing to different spaces on a multi-monitor setup is buggy.

My setup has one primary and two secondary monitors. The primary is connected to the macbook via DP->usb-c cable. The other two via a usb-c DisplayLink dock.
1. If I throw a window on one of the secondary monitors to space left / right, the window jumps to the primary monitor instead.
2. If I try to throw a window on the primary monitor to space right / left, I jump to that space but leave the window behind.
3. If I try to throw a window to a different monitor it doesn't usually work first time and I have to hit the hotkey two or three times to get it to move.

None of the above behaviors happen in v15.6.0

**Applications:**
All

**To Reproduce**
Attempt to throw windows between spaces and monitors on a multi-monitor arrangement on any version after 15.6.0

**Expected behavior**
Expect windows thrown to space left / right to stay on their original monitor, and move correctly to space left / right.
Expect windows thrown to other monitors to move first time.

**Screenshots**
N/A

**Versions:**
 - macOS: 12.6.3
 - Amethyst: >15.6.0 
 
**Debug Info**
```
Version: 0.16.1 (95)

OS version: Version 12.6.3 (Build 21G419)

Screens:
	(0.0, 0.0, 3840.0, 2160.0) [(0.0, 0.0, 3840.0, 2160.0)]
	(-1440.0, -253.0, 1440.0, 2560.0) [(-1440.0, -147.0, 1440.0, 2560.0)]
	(3840.0, -255.0, 1440.0, 2560.0) [(3840.0, -145.0, 1440.0, 2560.0)]

Configuration:
debug-layout-info: 0
window-margin-size: 15
smart-window-margins: 0
mouse-follows-focus: 1
mod1: (
    option,
    shift
)
mouse-swaps-windows: 0
screen-padding-right: 0
enables-layout-hud-on-space-change: 1
window-margins: 0
restore-layouts-on-launch: 1
float-small-windows: 1
new-windows-to-main: 0
layouts: (
    tall,
    wide,
    fullscreen,
    column,
    row,
    "middle-wide",
    "two-pane",
    bsp,
    "4column-right",
    "two-pane"
)
mouse-resizes-windows: 0
focus-follows-mouse: 0
screen-padding-left: 0
floating: (
        {
        id = "com.apple.systempreferences";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.calculator";
        "window-titles" =         (
        );
    }
)
follow-space-thrown-windows: 1
window-resize-step: 5
ignore-menu-bar: 0
enables-layout-hud: 1
mod2: (
    option,
    shift,
    control
)
window-minimum-width: 0
screen-padding-bottom: 0
window-minimum-height: 0
screen-padding-top: 0
floating-is-blacklist: 1
use-canary-build: 1
```

**Additional context**
None

**Comment by ianyh** [comment]
Both of those issues should be fixed in 0.19.0.

**Comment by lebedinj-aws** [comment]
I'm still seeing the same bug on 0.19.0. Specifically, when I throw a window to a different space, it ends up maximized on my primary display, instead of where it was on the original space. On 15.6.0 the behavior works fine. How do I get the debug info shown above?

**Comment by ianyh** [comment]
> I'm still seeing the same bug on 0.19.0. Specifically, when I throw a window to a different space, it ends up maximized on my primary display, instead of where it was on the original space. On 15.6.0 the behavior works fine. How do I get the debug info shown above?

That sounds like a different bug if you are seeing it on 0.19.0. Could you open a new issue?
