### ISSUE TITLE
Check for updates is broken?

### ISSUE THREAD

**Issue by caskolkm** [ianyh/Amethyst#332]
<img width="416" alt="screen shot 2015-10-16 at 15 11 15" src="https://cloud.githubusercontent.com/assets/2329830/10542416/4d5037a8-7418-11e5-9c8e-556ae78d4f7a.png">

[Trello Card](https://trello.com/c/AymxdkEZ/160-amethyst-check-for-updates-is-broken)

**Comment by ianyh** [comment]
Oof. See https://github.com/sparkle-project/Sparkle/issues/644. I can try to shim into 0.9.5, but that'll only be for future users. 0.9.5 will need to either be switched out manually or manually updated to 0.9.6 when it lands. I tested all of the update mechanisms, but not before I upgraded to 10.11, apparently.

**Comment by ianyh** [comment]
Temporarily removing 0.9.5 from appcast so more people don't update to it.

**Comment by ianyh** [comment]
Should be fixed in an updated 0.9.5. You may need to manually reinstall.

**Comment by rprimus** [comment]
Sat Oct 17 22:10:15 BST 2015

Just downloaded ```Amethyst-latest.zip``` from the link in ```Readme.md```, but still get the following errors when attempting to update:

```
Oct 17 22:07:35 rp-mbp Amethyst[77601]: Sparkle: ===== Amethyst =====
Oct 17 22:07:35 rp-mbp Amethyst[77601]: Sparkle: Error: An error occurred in retrieving update information. Please try again later. The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
```

Is there a way to get the zip for ```0.9.6b```?

**Comment by caskolkm** [comment]
Just re-installed it, but is isn't fixed.

**Comment by ianyh** [comment]
Okay, now this should be actually fixed. There was an additional bug that was preventing the appcast url from being updated, so it would only work if you were on the development channel. Still going to require a reinstall unfortunately.

**Comment by caskolkm** [comment]
@ianyh can you provide us a working development version?

**Comment by ianyh** [comment]
I should be able to push out a fix for 0.9.6b later today.

**Comment by caskolkm** [comment]
where can i find a development release of 0.9.6b?

**Comment by ianyh** [comment]
You can find it at http://ianyh.com/amethyst/versions/Amethyst-0.9.6b.zip, but if you have `Displays have separate spaces` turned off it won't work for you.

**Comment by rprimus** [comment]
Wed Oct 21 17:31:15 BST 2015

amethyst-latest.zip is 13 days old and does not point to 0.9.5.zip (updated 3 hours ago).

**Comment by ianyh** [comment]
Fixed.

**Comment by rprimus** [comment]
Wed Oct 21 18:33:02 BST 2015

Cheers.

Would it be easier to have Amethyst-latest be a symlink to the latest stable version?
Also, Amethyst-devel can be a symlink to the latest devel version.

A simple shell script could be used to manage the symlinks whenever there is a new stable/devel version.

**Comment by ianyh** [comment]
Yeah, that probably makes sense. `Amethyst-latest.zip` doesn't get used very often, though. At least I don't use it. I'll still do the symlink, though.

**Comment by rprimus** [comment]
Wed Oct 21 20:42:28 BST 2015

```Amethyst-latest.zip``` is referenced at here at [```Getting Amethyst```](http://ianyh.com/amethyst/).

```html
<p>Amethyst is available for direct download <a href="http://ianyh.com/amethyst/versions/Amethyst-latest.zip">here</a>
```

**Comment by ianyh** [comment]
Huh. You're right.

**Comment by ianyh** [comment]
0.9.6b2 is out and should solve a lot of these problems.
