### ISSUE TITLE
0.9.6b doesn't move windows at all

### ISSUE THREAD

**Issue by brianhv** [ianyh/Amethyst#333]
I tried updating to 0.9.6b to get the fix for #207. Unfortunately, this version isn't moving my windows at all. The HUD appears, but nothing changes. If I revert to 0.9.5, tiling works as expected.

Macbook Pro (15 inch, mid-2010), OSX 10.10.4. Amethyst is listed as permitted in the accessibility section of the Security & Privacy control panel.

[Trello Card](https://trello.com/c/z4RIbkIJ/161-amethyst-0-9-6b-doesn-t-move-windows-at-all)

**Comment by amfarrell** [comment]
I can reproduce this experience. Updating to 0.9.6b also caused amethyst to no longer move windows around. I tried unsetting and then resetting the accessability permissions, but that didn't work. After downloading http://ianyh.com/amethyst/versions/Amethyst-0.9.5.zip, installing that, and quitting the newer version of Amethyst, it works again.

**Comment by ianyh** [comment]
Thanks for the heads up. Not sure what went wrong. Downgraded the development channel for now. I'm offline probably until Sunday.

**Comment by thomaskern** [comment]
Same problem. in Console the only amethyst related output  i see is 
```
18/10/15 12:10:33,250 Amethyst[61127]: Failed to connect (containerView) outlet from (AMLayoutNameWindow) to (NSView): missing setter or instance variable
```

**Comment by ianyh** [comment]
Tested this now that I'm at a multi-monitor set up and can confirm that it's fixed. Will go out in 0.9.6b2. Hopefully that will be soon.

**Comment by thomaskern** [comment]
Just updated to the new version. Still the same issue

**Comment by ianyh** [comment]
Do you have Screens have separate spaces turned on in the Mission Control preferences?

**Comment by ianyh** [comment]
Also can anyone else confirm?

**Comment by thomaskern** [comment]
![mission_control](https://cloud.githubusercontent.com/assets/39680/10691041/f87ff2de-797d-11e5-94a8-69d40380f992.png)

**Comment by ianyh** [comment]
Hm. That's definitely the problem I fixed. I can test it again later. In the meantime, can you try toggling Amethyst in the Accessibility tab on Privacy settings as quick check

**Comment by thomaskern** [comment]
Done and no change. I see "Tall" popping up on both screens but no movement on the windows.

**Comment by ianyh** [comment]
Okay. I'll take another look when I get a chance. Thanks for the thorough
info.

**Comment by ianyh** [comment]
It looks like it's working for me with separate spaces off, which is the bug I fixed previously. Are you sure you're on 0.9.6b2? The version number should at the top of the dropdown menu from the menu bar icon.

**Comment by thomaskern** [comment]
yup, 0.9.6b2 (25).

i will log out and see if it changes

-- thomas

**Comment by brianhv** [comment]
Also tried updating, still seeing the same issue. Only have the MBP's display right now; no external. "Displays have separate spaces" is off. The Amethyst menu says "Version 0.9.6b2 (25)".

**Comment by thomaskern** [comment]
Logout did not help ;)

**Comment by ianyh** [comment]
Ugh. Alright. I'll do some more digging and hopefully get a fix out. Sorry for this, and thank you for bearing with me.

**Comment by ianyh** [comment]
Is everyone running OS X 10.11?

**Comment by thomaskern** [comment]
i am running 10.10.3 (14D136)

**Comment by thomaskern** [comment]
I am running 10.10.3 (14D136)

-- thomas

**Comment by ianyh** [comment]
Ugh. I don't have a way to test 10.10 anymore. :(

Let me see if I can still figure this out.

**Comment by thomaskern** [comment]
I just upgraded to 10.11.1 to see if it changes anything for amethyst. we
are back in business. after the upgrade, windows are being resized and
placed properly.

-- thomas

**Comment by ianyh** [comment]
That's obnoxious. The danger of private APIs I suppose. I guess I have to change the os version requirement to 0.9.6.

**Comment by ianyh** [comment]
Temporarily back supporting 10.10. 0.9.6 will probably be the last version to support it.
